tap "homebrew/bundle"
tap "homebrew/core"

cask "docker"
cask "slack"
cask "discord"
cask "zoom"
cask "forticlient"
cask "whatsapp"
cask "notion"
cask "parsec"
cask "appcleaner"
cask "grammarly"
cask "gpg-suite"
